MusicApp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :users, only: [:create, :new, :show]

  resource :session, only: [:new, :create, :destroy]
end

MusicApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

MusicApp/app/models/user.rb
class User < ApplicationRecord
    validates :email,:session_token, presence: true, uniqueness: true 
    validates :password, length: {minimum: 6}, allow_nil: true 
    validates :password_digest, presence: true 

    after_initialize :ensure_session_token
   
    attr_reader :password

    def self.find_by_credentials(email, password)
        debugger
        user = User.find_by(email: email)
        
        if user && user.is_password?(password)
            user
        else 
            nil 
        end
    end
    
    def is_password?(password)
        pass = Bcrypt::Password.new(password_digest)
        pass.is_password?(password)
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
        @password = password
    end

    def generate_unique_session_token
        loop do
            session_token = SecureRandom::urlsafe_base64
            return session_token unless User.exists?(session_token: session_token)
        end
    end

    def reset_session_token!
        self.session_token = generate_unique_session_token
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= generate_unique_session_token
    end
end

MusicApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    skip_before_action :verify_authenticity_token
    helper_method :current_user, :logged_in?
    
    def current_user 
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login!(user)
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        !!current_user
    end

    def logout!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end
end

MusicApp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

    def new
        @user = User.new

        render :new
    end

    def create 
        email = params[:user][:email]
        password = params[:user][:password]
        debugger
        @user = User.find_by_credentials(email,password)

        if @user
            login!(@user)
            # redirect_to user_url(@user)
        else
            @user = User.new(email: email)
            flash.now[:errors] = ["Invalid Credentials"]
            render :new 
        end
    end

    def destroy 
        if logged_in?
            logout!
            redirect_to new_user_url
        else
            flash[:messages] = ["Successfully logged out"]
            # redirect_to new_session_url 
        end
    end
end

MusicApp/app/controllers/users_controller.rb
class UsersController < ApplicationController 
    
    # def index 
    #     @users = User.all 
    #     render :index 
    # end
    
    def show 
        @user = User.find_by(id: params[:id])
        render :show 
    end

    def new
        @user = User.new

        render :new
    end

    def create 
        @user = User.new(user_params)

        if @user.save! 
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @users.errors.full_messages
            render :new 
        end
    end

    private 

    def user_params
        params.require(:user).permit(:email,:password)
    end
end

MusicApp/app/helpers/application_helper.rb
module ApplicationHelper
end

MusicApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <style>
      /* Add snazzy font */
      @import url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
      body {
        font-family: 'Montserrat', sans-serif;
      }

      /* Flexbox to display logged-in or logged-out info on the right-hand side */
      header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        padding: 20px;
        background-color: #333;
        color: #fff;
      }
      .logo {
        font-size: 30px;
        font-weight: bold;
      }
      .user-info {
        display: flex;
        align-items: center;
      }
      .user-info img {
        width: 30px;
        height: 30px;
        border-radius: 50%;
        margin-right: 10px;
      }

      /* Default link styling */
      a {
        color: #333;
        text-decoration: none;
        padding: 10px;
        border-radius: 5px;
        background-color: #eee;
      }
      a:hover {
        background-color: #ddd;
      }

      /* Session form styling */
      form {
        display: flex;
        flex-direction: column;
        align-items: center;
        margin-top: 50px;
      }
      label {
        margin-bottom: 10px;
      }
      input[type="text"],
      input[type="password"] {
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #ccc;
        margin-bottom: 20px;
        width: 100%;
      }
      input[type="submit"] {
        background-color: #333;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
      }
      input[type="submit"]:hover {
        background-color: #555;
      }
    </style>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>

  <% if logged_in? %>
      <h2>Welcome, <%= current_user.email %></h2>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>

        <input type="submit" value="Sign-Out">

      </form>
    <% else %>
      <a href="<%= new_user_url %>">Sign Up</a>
      <a href="<%= new_session_url %>">Sign In</a>
    <% end%>
    <%= yield %>
  </body>
</html>

MusicApp/app/views/users/new.html.erb
<form action="<%=users_url%>" method="POST">

<input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

<label for="email">Email:
    <input type="text" id="email" name="user[email]" value="<%=@user.email%>">
</label>

<label for="password">Password:
    <input type="password" id="password" name="user[password]" value="">
</label>

<input type="submit" value="Log In">

</form>

MusicApp/app/views/users/show.html.erb
<h1>User Profile</h1>

<p>Email value="<%=@user.email%>"</p>